# Generated by Django 4.0.4 on 2022-04-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('secondaryPhoneNumber', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital', models.CharField(max_length=300)),
                ('years_of_experience', models.CharField(max_length=30)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
    ]
